/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.rtrs.events.common;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Common metadata attached to every domain event in RTRS */
@org.apache.avro.specific.AvroGenerated
public class EventMetadata extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7881088196180834472L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EventMetadata\",\"namespace\":\"com.rtrs.events.common\",\"doc\":\"Common metadata attached to every domain event in RTRS\",\"fields\":[{\"name\":\"eventId\",\"type\":\"string\",\"doc\":\"UUID uniquely identifying this event instance\"},{\"name\":\"eventVersion\",\"type\":\"int\",\"doc\":\"Schema version of this event\",\"default\":1},{\"name\":\"eventType\",\"type\":\"string\",\"doc\":\"Fully qualified event type name\"},{\"name\":\"correlationId\",\"type\":\"string\",\"doc\":\"UUID linking all events in a single trade lifecycle\"},{\"name\":\"causationId\",\"type\":\"string\",\"doc\":\"UUID of the event that caused this event\"},{\"name\":\"source\",\"type\":\"string\",\"doc\":\"Service that published this event\"},{\"name\":\"publishedAt\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"},\"doc\":\"Epoch millis when event was published\"},{\"name\":\"traceId\",\"type\":[\"null\",\"string\"],\"doc\":\"OpenTelemetry trace ID for distributed tracing\",\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<EventMetadata> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<EventMetadata> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<EventMetadata> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<EventMetadata> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<EventMetadata> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this EventMetadata to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a EventMetadata from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a EventMetadata instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static EventMetadata fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** UUID uniquely identifying this event instance */
  private java.lang.CharSequence eventId;
  /** Schema version of this event */
  private int eventVersion;
  /** Fully qualified event type name */
  private java.lang.CharSequence eventType;
  /** UUID linking all events in a single trade lifecycle */
  private java.lang.CharSequence correlationId;
  /** UUID of the event that caused this event */
  private java.lang.CharSequence causationId;
  /** Service that published this event */
  private java.lang.CharSequence source;
  /** Epoch millis when event was published */
  private java.time.Instant publishedAt;
  /** OpenTelemetry trace ID for distributed tracing */
  private java.lang.CharSequence traceId;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public EventMetadata() {}

  /**
   * All-args constructor.
   * @param eventId UUID uniquely identifying this event instance
   * @param eventVersion Schema version of this event
   * @param eventType Fully qualified event type name
   * @param correlationId UUID linking all events in a single trade lifecycle
   * @param causationId UUID of the event that caused this event
   * @param source Service that published this event
   * @param publishedAt Epoch millis when event was published
   * @param traceId OpenTelemetry trace ID for distributed tracing
   */
  public EventMetadata(java.lang.CharSequence eventId, java.lang.Integer eventVersion, java.lang.CharSequence eventType, java.lang.CharSequence correlationId, java.lang.CharSequence causationId, java.lang.CharSequence source, java.time.Instant publishedAt, java.lang.CharSequence traceId) {
    this.eventId = eventId;
    this.eventVersion = eventVersion;
    this.eventType = eventType;
    this.correlationId = correlationId;
    this.causationId = causationId;
    this.source = source;
    this.publishedAt = publishedAt.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
    this.traceId = traceId;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return eventId;
    case 1: return eventVersion;
    case 2: return eventType;
    case 3: return correlationId;
    case 4: return causationId;
    case 5: return source;
    case 6: return publishedAt;
    case 7: return traceId;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null,
      null,
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: eventId = (java.lang.CharSequence)value$; break;
    case 1: eventVersion = (java.lang.Integer)value$; break;
    case 2: eventType = (java.lang.CharSequence)value$; break;
    case 3: correlationId = (java.lang.CharSequence)value$; break;
    case 4: causationId = (java.lang.CharSequence)value$; break;
    case 5: source = (java.lang.CharSequence)value$; break;
    case 6: publishedAt = (java.time.Instant)value$; break;
    case 7: traceId = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'eventId' field.
   * @return UUID uniquely identifying this event instance
   */
  public java.lang.CharSequence getEventId() {
    return eventId;
  }


  /**
   * Sets the value of the 'eventId' field.
   * UUID uniquely identifying this event instance
   * @param value the value to set.
   */
  public void setEventId(java.lang.CharSequence value) {
    this.eventId = value;
  }

  /**
   * Gets the value of the 'eventVersion' field.
   * @return Schema version of this event
   */
  public int getEventVersion() {
    return eventVersion;
  }


  /**
   * Sets the value of the 'eventVersion' field.
   * Schema version of this event
   * @param value the value to set.
   */
  public void setEventVersion(int value) {
    this.eventVersion = value;
  }

  /**
   * Gets the value of the 'eventType' field.
   * @return Fully qualified event type name
   */
  public java.lang.CharSequence getEventType() {
    return eventType;
  }


  /**
   * Sets the value of the 'eventType' field.
   * Fully qualified event type name
   * @param value the value to set.
   */
  public void setEventType(java.lang.CharSequence value) {
    this.eventType = value;
  }

  /**
   * Gets the value of the 'correlationId' field.
   * @return UUID linking all events in a single trade lifecycle
   */
  public java.lang.CharSequence getCorrelationId() {
    return correlationId;
  }


  /**
   * Sets the value of the 'correlationId' field.
   * UUID linking all events in a single trade lifecycle
   * @param value the value to set.
   */
  public void setCorrelationId(java.lang.CharSequence value) {
    this.correlationId = value;
  }

  /**
   * Gets the value of the 'causationId' field.
   * @return UUID of the event that caused this event
   */
  public java.lang.CharSequence getCausationId() {
    return causationId;
  }


  /**
   * Sets the value of the 'causationId' field.
   * UUID of the event that caused this event
   * @param value the value to set.
   */
  public void setCausationId(java.lang.CharSequence value) {
    this.causationId = value;
  }

  /**
   * Gets the value of the 'source' field.
   * @return Service that published this event
   */
  public java.lang.CharSequence getSource() {
    return source;
  }


  /**
   * Sets the value of the 'source' field.
   * Service that published this event
   * @param value the value to set.
   */
  public void setSource(java.lang.CharSequence value) {
    this.source = value;
  }

  /**
   * Gets the value of the 'publishedAt' field.
   * @return Epoch millis when event was published
   */
  public java.time.Instant getPublishedAt() {
    return publishedAt;
  }


  /**
   * Sets the value of the 'publishedAt' field.
   * Epoch millis when event was published
   * @param value the value to set.
   */
  public void setPublishedAt(java.time.Instant value) {
    this.publishedAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Gets the value of the 'traceId' field.
   * @return OpenTelemetry trace ID for distributed tracing
   */
  public java.lang.CharSequence getTraceId() {
    return traceId;
  }


  /**
   * Sets the value of the 'traceId' field.
   * OpenTelemetry trace ID for distributed tracing
   * @param value the value to set.
   */
  public void setTraceId(java.lang.CharSequence value) {
    this.traceId = value;
  }

  /**
   * Creates a new EventMetadata RecordBuilder.
   * @return A new EventMetadata RecordBuilder
   */
  public static com.rtrs.events.common.EventMetadata.Builder newBuilder() {
    return new com.rtrs.events.common.EventMetadata.Builder();
  }

  /**
   * Creates a new EventMetadata RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new EventMetadata RecordBuilder
   */
  public static com.rtrs.events.common.EventMetadata.Builder newBuilder(com.rtrs.events.common.EventMetadata.Builder other) {
    if (other == null) {
      return new com.rtrs.events.common.EventMetadata.Builder();
    } else {
      return new com.rtrs.events.common.EventMetadata.Builder(other);
    }
  }

  /**
   * Creates a new EventMetadata RecordBuilder by copying an existing EventMetadata instance.
   * @param other The existing instance to copy.
   * @return A new EventMetadata RecordBuilder
   */
  public static com.rtrs.events.common.EventMetadata.Builder newBuilder(com.rtrs.events.common.EventMetadata other) {
    if (other == null) {
      return new com.rtrs.events.common.EventMetadata.Builder();
    } else {
      return new com.rtrs.events.common.EventMetadata.Builder(other);
    }
  }

  /**
   * RecordBuilder for EventMetadata instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EventMetadata>
    implements org.apache.avro.data.RecordBuilder<EventMetadata> {

    /** UUID uniquely identifying this event instance */
    private java.lang.CharSequence eventId;
    /** Schema version of this event */
    private int eventVersion;
    /** Fully qualified event type name */
    private java.lang.CharSequence eventType;
    /** UUID linking all events in a single trade lifecycle */
    private java.lang.CharSequence correlationId;
    /** UUID of the event that caused this event */
    private java.lang.CharSequence causationId;
    /** Service that published this event */
    private java.lang.CharSequence source;
    /** Epoch millis when event was published */
    private java.time.Instant publishedAt;
    /** OpenTelemetry trace ID for distributed tracing */
    private java.lang.CharSequence traceId;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.rtrs.events.common.EventMetadata.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.eventId)) {
        this.eventId = data().deepCopy(fields()[0].schema(), other.eventId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.eventVersion)) {
        this.eventVersion = data().deepCopy(fields()[1].schema(), other.eventVersion);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.eventType)) {
        this.eventType = data().deepCopy(fields()[2].schema(), other.eventType);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.correlationId)) {
        this.correlationId = data().deepCopy(fields()[3].schema(), other.correlationId);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.causationId)) {
        this.causationId = data().deepCopy(fields()[4].schema(), other.causationId);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.source)) {
        this.source = data().deepCopy(fields()[5].schema(), other.source);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.publishedAt)) {
        this.publishedAt = data().deepCopy(fields()[6].schema(), other.publishedAt);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.traceId)) {
        this.traceId = data().deepCopy(fields()[7].schema(), other.traceId);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
    }

    /**
     * Creates a Builder by copying an existing EventMetadata instance
     * @param other The existing instance to copy.
     */
    private Builder(com.rtrs.events.common.EventMetadata other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.eventId)) {
        this.eventId = data().deepCopy(fields()[0].schema(), other.eventId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.eventVersion)) {
        this.eventVersion = data().deepCopy(fields()[1].schema(), other.eventVersion);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.eventType)) {
        this.eventType = data().deepCopy(fields()[2].schema(), other.eventType);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.correlationId)) {
        this.correlationId = data().deepCopy(fields()[3].schema(), other.correlationId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.causationId)) {
        this.causationId = data().deepCopy(fields()[4].schema(), other.causationId);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.source)) {
        this.source = data().deepCopy(fields()[5].schema(), other.source);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.publishedAt)) {
        this.publishedAt = data().deepCopy(fields()[6].schema(), other.publishedAt);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.traceId)) {
        this.traceId = data().deepCopy(fields()[7].schema(), other.traceId);
        fieldSetFlags()[7] = true;
      }
    }

    /**
      * Gets the value of the 'eventId' field.
      * UUID uniquely identifying this event instance
      * @return The value.
      */
    public java.lang.CharSequence getEventId() {
      return eventId;
    }


    /**
      * Sets the value of the 'eventId' field.
      * UUID uniquely identifying this event instance
      * @param value The value of 'eventId'.
      * @return This builder.
      */
    public com.rtrs.events.common.EventMetadata.Builder setEventId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.eventId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'eventId' field has been set.
      * UUID uniquely identifying this event instance
      * @return True if the 'eventId' field has been set, false otherwise.
      */
    public boolean hasEventId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'eventId' field.
      * UUID uniquely identifying this event instance
      * @return This builder.
      */
    public com.rtrs.events.common.EventMetadata.Builder clearEventId() {
      eventId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'eventVersion' field.
      * Schema version of this event
      * @return The value.
      */
    public int getEventVersion() {
      return eventVersion;
    }


    /**
      * Sets the value of the 'eventVersion' field.
      * Schema version of this event
      * @param value The value of 'eventVersion'.
      * @return This builder.
      */
    public com.rtrs.events.common.EventMetadata.Builder setEventVersion(int value) {
      validate(fields()[1], value);
      this.eventVersion = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'eventVersion' field has been set.
      * Schema version of this event
      * @return True if the 'eventVersion' field has been set, false otherwise.
      */
    public boolean hasEventVersion() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'eventVersion' field.
      * Schema version of this event
      * @return This builder.
      */
    public com.rtrs.events.common.EventMetadata.Builder clearEventVersion() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'eventType' field.
      * Fully qualified event type name
      * @return The value.
      */
    public java.lang.CharSequence getEventType() {
      return eventType;
    }


    /**
      * Sets the value of the 'eventType' field.
      * Fully qualified event type name
      * @param value The value of 'eventType'.
      * @return This builder.
      */
    public com.rtrs.events.common.EventMetadata.Builder setEventType(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.eventType = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'eventType' field has been set.
      * Fully qualified event type name
      * @return True if the 'eventType' field has been set, false otherwise.
      */
    public boolean hasEventType() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'eventType' field.
      * Fully qualified event type name
      * @return This builder.
      */
    public com.rtrs.events.common.EventMetadata.Builder clearEventType() {
      eventType = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'correlationId' field.
      * UUID linking all events in a single trade lifecycle
      * @return The value.
      */
    public java.lang.CharSequence getCorrelationId() {
      return correlationId;
    }


    /**
      * Sets the value of the 'correlationId' field.
      * UUID linking all events in a single trade lifecycle
      * @param value The value of 'correlationId'.
      * @return This builder.
      */
    public com.rtrs.events.common.EventMetadata.Builder setCorrelationId(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.correlationId = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'correlationId' field has been set.
      * UUID linking all events in a single trade lifecycle
      * @return True if the 'correlationId' field has been set, false otherwise.
      */
    public boolean hasCorrelationId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'correlationId' field.
      * UUID linking all events in a single trade lifecycle
      * @return This builder.
      */
    public com.rtrs.events.common.EventMetadata.Builder clearCorrelationId() {
      correlationId = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'causationId' field.
      * UUID of the event that caused this event
      * @return The value.
      */
    public java.lang.CharSequence getCausationId() {
      return causationId;
    }


    /**
      * Sets the value of the 'causationId' field.
      * UUID of the event that caused this event
      * @param value The value of 'causationId'.
      * @return This builder.
      */
    public com.rtrs.events.common.EventMetadata.Builder setCausationId(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.causationId = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'causationId' field has been set.
      * UUID of the event that caused this event
      * @return True if the 'causationId' field has been set, false otherwise.
      */
    public boolean hasCausationId() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'causationId' field.
      * UUID of the event that caused this event
      * @return This builder.
      */
    public com.rtrs.events.common.EventMetadata.Builder clearCausationId() {
      causationId = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'source' field.
      * Service that published this event
      * @return The value.
      */
    public java.lang.CharSequence getSource() {
      return source;
    }


    /**
      * Sets the value of the 'source' field.
      * Service that published this event
      * @param value The value of 'source'.
      * @return This builder.
      */
    public com.rtrs.events.common.EventMetadata.Builder setSource(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.source = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'source' field has been set.
      * Service that published this event
      * @return True if the 'source' field has been set, false otherwise.
      */
    public boolean hasSource() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'source' field.
      * Service that published this event
      * @return This builder.
      */
    public com.rtrs.events.common.EventMetadata.Builder clearSource() {
      source = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'publishedAt' field.
      * Epoch millis when event was published
      * @return The value.
      */
    public java.time.Instant getPublishedAt() {
      return publishedAt;
    }


    /**
      * Sets the value of the 'publishedAt' field.
      * Epoch millis when event was published
      * @param value The value of 'publishedAt'.
      * @return This builder.
      */
    public com.rtrs.events.common.EventMetadata.Builder setPublishedAt(java.time.Instant value) {
      validate(fields()[6], value);
      this.publishedAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'publishedAt' field has been set.
      * Epoch millis when event was published
      * @return True if the 'publishedAt' field has been set, false otherwise.
      */
    public boolean hasPublishedAt() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'publishedAt' field.
      * Epoch millis when event was published
      * @return This builder.
      */
    public com.rtrs.events.common.EventMetadata.Builder clearPublishedAt() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'traceId' field.
      * OpenTelemetry trace ID for distributed tracing
      * @return The value.
      */
    public java.lang.CharSequence getTraceId() {
      return traceId;
    }


    /**
      * Sets the value of the 'traceId' field.
      * OpenTelemetry trace ID for distributed tracing
      * @param value The value of 'traceId'.
      * @return This builder.
      */
    public com.rtrs.events.common.EventMetadata.Builder setTraceId(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.traceId = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'traceId' field has been set.
      * OpenTelemetry trace ID for distributed tracing
      * @return True if the 'traceId' field has been set, false otherwise.
      */
    public boolean hasTraceId() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'traceId' field.
      * OpenTelemetry trace ID for distributed tracing
      * @return This builder.
      */
    public com.rtrs.events.common.EventMetadata.Builder clearTraceId() {
      traceId = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public EventMetadata build() {
      try {
        EventMetadata record = new EventMetadata();
        record.eventId = fieldSetFlags()[0] ? this.eventId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.eventVersion = fieldSetFlags()[1] ? this.eventVersion : (java.lang.Integer) defaultValue(fields()[1]);
        record.eventType = fieldSetFlags()[2] ? this.eventType : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.correlationId = fieldSetFlags()[3] ? this.correlationId : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.causationId = fieldSetFlags()[4] ? this.causationId : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.source = fieldSetFlags()[5] ? this.source : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.publishedAt = fieldSetFlags()[6] ? this.publishedAt : (java.time.Instant) defaultValue(fields()[6]);
        record.traceId = fieldSetFlags()[7] ? this.traceId : (java.lang.CharSequence) defaultValue(fields()[7]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<EventMetadata>
    WRITER$ = (org.apache.avro.io.DatumWriter<EventMetadata>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<EventMetadata>
    READER$ = (org.apache.avro.io.DatumReader<EventMetadata>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










