package com.rtrs.common.enums;

public enum ErrorCode {

    VALIDATION_FAILED,
    INVALID_PARAMETER,
    MALFORMED_REQUEST,

    UNAUTHORIZED,
    FORBIDDEN,

    RESOURCE_NOT_FOUND,
    RESOURCE_ALREADY_EXISTS,
    RESOURCE_CONFLICT,

    BUSINESS_RULE_VIOLATION,

    DATABASE_ERROR,
    EXTERNAL_SERVICE_ERROR,

    INTERNAL_ERROR
}