/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.rtrs.events.trade;
@org.apache.avro.specific.AvroGenerated
public enum ExecutionStatus implements org.apache.avro.generic.GenericEnumSymbol<ExecutionStatus> {
  FILLED, PARTIALLY_FILLED, REJECTED, CANCELLED, EXPIRED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ExecutionStatus\",\"namespace\":\"com.rtrs.events.trade\",\"symbols\":[\"FILLED\",\"PARTIALLY_FILLED\",\"REJECTED\",\"CANCELLED\",\"EXPIRED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
