/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.rtrs.events.trade;
@org.apache.avro.specific.AvroGenerated
public enum RejectionReason implements org.apache.avro.generic.GenericEnumSymbol<RejectionReason> {
  RISK_BREACH, AML_FLAGGED, VALIDATION_FAILED, INSUFFICIENT_FUNDS, MARKET_CLOSED, TIMEOUT, INTERNAL_ERROR  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"RejectionReason\",\"namespace\":\"com.rtrs.events.trade\",\"symbols\":[\"RISK_BREACH\",\"AML_FLAGGED\",\"VALIDATION_FAILED\",\"INSUFFICIENT_FUNDS\",\"MARKET_CLOSED\",\"TIMEOUT\",\"INTERNAL_ERROR\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
