/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.rtrs.events.trade;
/** Direction and type of a trade order */
@org.apache.avro.specific.AvroGenerated
public enum TradeType implements org.apache.avro.generic.GenericEnumSymbol<TradeType> {
  BUY, SELL, SHORT, COVER  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"TradeType\",\"namespace\":\"com.rtrs.events.trade\",\"doc\":\"Direction and type of a trade order\",\"symbols\":[\"BUY\",\"SELL\",\"SHORT\",\"COVER\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
