/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.rtrs.events.risk;
@org.apache.avro.specific.AvroGenerated
public enum BreachType implements org.apache.avro.generic.GenericEnumSymbol<BreachType> {
  POSITION_LIMIT, VAR_LIMIT, MARGIN_BREACH, CONCENTRATION_LIMIT, INTRADAY_EXPOSURE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"BreachType\",\"namespace\":\"com.rtrs.events.risk\",\"symbols\":[\"POSITION_LIMIT\",\"VAR_LIMIT\",\"MARGIN_BREACH\",\"CONCENTRATION_LIMIT\",\"INTRADAY_EXPOSURE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
