/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.rtrs.events.ledger;
@org.apache.avro.specific.AvroGenerated
public enum EntryType implements org.apache.avro.generic.GenericEnumSymbol<EntryType> {
  DEBIT, CREDIT  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"EntryType\",\"namespace\":\"com.rtrs.events.ledger\",\"symbols\":[\"DEBIT\",\"CREDIT\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
