/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.rtrs.events.aml;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Published when a trade passes all AML checks */
@org.apache.avro.specific.AvroGenerated
public class AmlClearedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7305685332543607430L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AmlClearedEvent\",\"namespace\":\"com.rtrs.events.aml\",\"doc\":\"Published when a trade passes all AML checks\",\"fields\":[{\"name\":\"metadata\",\"type\":{\"type\":\"record\",\"name\":\"EventMetadata\",\"namespace\":\"com.rtrs.events.common\",\"doc\":\"Common metadata attached to every domain event in RTRS\",\"fields\":[{\"name\":\"eventId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"UUID uniquely identifying this event instance\"},{\"name\":\"eventVersion\",\"type\":\"int\",\"doc\":\"Schema version of this event\",\"default\":1},{\"name\":\"eventType\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Fully qualified event type name\"},{\"name\":\"correlationId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"UUID linking all events in a single trade lifecycle\"},{\"name\":\"causationId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"UUID of the event that caused this event\"},{\"name\":\"source\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Service that published this event\"},{\"name\":\"publishedAt\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"},\"doc\":\"Epoch millis when event was published\"},{\"name\":\"traceId\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"OpenTelemetry trace ID for distributed tracing\",\"default\":null}]}},{\"name\":\"tradeId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"accountId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"riskScore\",\"type\":\"int\",\"doc\":\"AML risk score 0-100, threshold is 70\"},{\"name\":\"clearedAt\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<AmlClearedEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AmlClearedEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AmlClearedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AmlClearedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AmlClearedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AmlClearedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AmlClearedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AmlClearedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AmlClearedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private com.rtrs.events.common.EventMetadata metadata;
  private java.lang.String tradeId;
  private java.lang.String accountId;
  /** AML risk score 0-100, threshold is 70 */
  private int riskScore;
  private java.time.Instant clearedAt;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AmlClearedEvent() {}

  /**
   * All-args constructor.
   * @param metadata The new value for metadata
   * @param tradeId The new value for tradeId
   * @param accountId The new value for accountId
   * @param riskScore AML risk score 0-100, threshold is 70
   * @param clearedAt The new value for clearedAt
   */
  public AmlClearedEvent(com.rtrs.events.common.EventMetadata metadata, java.lang.String tradeId, java.lang.String accountId, java.lang.Integer riskScore, java.time.Instant clearedAt) {
    this.metadata = metadata;
    this.tradeId = tradeId;
    this.accountId = accountId;
    this.riskScore = riskScore;
    this.clearedAt = clearedAt.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return metadata;
    case 1: return tradeId;
    case 2: return accountId;
    case 3: return riskScore;
    case 4: return clearedAt;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: metadata = (com.rtrs.events.common.EventMetadata)value$; break;
    case 1: tradeId = value$ != null ? value$.toString() : null; break;
    case 2: accountId = value$ != null ? value$.toString() : null; break;
    case 3: riskScore = (java.lang.Integer)value$; break;
    case 4: clearedAt = (java.time.Instant)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'metadata' field.
   * @return The value of the 'metadata' field.
   */
  public com.rtrs.events.common.EventMetadata getMetadata() {
    return metadata;
  }


  /**
   * Sets the value of the 'metadata' field.
   * @param value the value to set.
   */
  public void setMetadata(com.rtrs.events.common.EventMetadata value) {
    this.metadata = value;
  }

  /**
   * Gets the value of the 'tradeId' field.
   * @return The value of the 'tradeId' field.
   */
  public java.lang.String getTradeId() {
    return tradeId;
  }


  /**
   * Sets the value of the 'tradeId' field.
   * @param value the value to set.
   */
  public void setTradeId(java.lang.String value) {
    this.tradeId = value;
  }

  /**
   * Gets the value of the 'accountId' field.
   * @return The value of the 'accountId' field.
   */
  public java.lang.String getAccountId() {
    return accountId;
  }


  /**
   * Sets the value of the 'accountId' field.
   * @param value the value to set.
   */
  public void setAccountId(java.lang.String value) {
    this.accountId = value;
  }

  /**
   * Gets the value of the 'riskScore' field.
   * @return AML risk score 0-100, threshold is 70
   */
  public int getRiskScore() {
    return riskScore;
  }


  /**
   * Sets the value of the 'riskScore' field.
   * AML risk score 0-100, threshold is 70
   * @param value the value to set.
   */
  public void setRiskScore(int value) {
    this.riskScore = value;
  }

  /**
   * Gets the value of the 'clearedAt' field.
   * @return The value of the 'clearedAt' field.
   */
  public java.time.Instant getClearedAt() {
    return clearedAt;
  }


  /**
   * Sets the value of the 'clearedAt' field.
   * @param value the value to set.
   */
  public void setClearedAt(java.time.Instant value) {
    this.clearedAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Creates a new AmlClearedEvent RecordBuilder.
   * @return A new AmlClearedEvent RecordBuilder
   */
  public static com.rtrs.events.aml.AmlClearedEvent.Builder newBuilder() {
    return new com.rtrs.events.aml.AmlClearedEvent.Builder();
  }

  /**
   * Creates a new AmlClearedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AmlClearedEvent RecordBuilder
   */
  public static com.rtrs.events.aml.AmlClearedEvent.Builder newBuilder(com.rtrs.events.aml.AmlClearedEvent.Builder other) {
    if (other == null) {
      return new com.rtrs.events.aml.AmlClearedEvent.Builder();
    } else {
      return new com.rtrs.events.aml.AmlClearedEvent.Builder(other);
    }
  }

  /**
   * Creates a new AmlClearedEvent RecordBuilder by copying an existing AmlClearedEvent instance.
   * @param other The existing instance to copy.
   * @return A new AmlClearedEvent RecordBuilder
   */
  public static com.rtrs.events.aml.AmlClearedEvent.Builder newBuilder(com.rtrs.events.aml.AmlClearedEvent other) {
    if (other == null) {
      return new com.rtrs.events.aml.AmlClearedEvent.Builder();
    } else {
      return new com.rtrs.events.aml.AmlClearedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for AmlClearedEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AmlClearedEvent>
    implements org.apache.avro.data.RecordBuilder<AmlClearedEvent> {

    private com.rtrs.events.common.EventMetadata metadata;
    private com.rtrs.events.common.EventMetadata.Builder metadataBuilder;
    private java.lang.String tradeId;
    private java.lang.String accountId;
    /** AML risk score 0-100, threshold is 70 */
    private int riskScore;
    private java.time.Instant clearedAt;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.rtrs.events.aml.AmlClearedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.metadata)) {
        this.metadata = data().deepCopy(fields()[0].schema(), other.metadata);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (other.hasMetadataBuilder()) {
        this.metadataBuilder = com.rtrs.events.common.EventMetadata.newBuilder(other.getMetadataBuilder());
      }
      if (isValidValue(fields()[1], other.tradeId)) {
        this.tradeId = data().deepCopy(fields()[1].schema(), other.tradeId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.accountId)) {
        this.accountId = data().deepCopy(fields()[2].schema(), other.accountId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.riskScore)) {
        this.riskScore = data().deepCopy(fields()[3].schema(), other.riskScore);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.clearedAt)) {
        this.clearedAt = data().deepCopy(fields()[4].schema(), other.clearedAt);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing AmlClearedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.rtrs.events.aml.AmlClearedEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.metadata)) {
        this.metadata = data().deepCopy(fields()[0].schema(), other.metadata);
        fieldSetFlags()[0] = true;
      }
      this.metadataBuilder = null;
      if (isValidValue(fields()[1], other.tradeId)) {
        this.tradeId = data().deepCopy(fields()[1].schema(), other.tradeId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.accountId)) {
        this.accountId = data().deepCopy(fields()[2].schema(), other.accountId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.riskScore)) {
        this.riskScore = data().deepCopy(fields()[3].schema(), other.riskScore);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.clearedAt)) {
        this.clearedAt = data().deepCopy(fields()[4].schema(), other.clearedAt);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'metadata' field.
      * @return The value.
      */
    public com.rtrs.events.common.EventMetadata getMetadata() {
      return metadata;
    }


    /**
      * Sets the value of the 'metadata' field.
      * @param value The value of 'metadata'.
      * @return This builder.
      */
    public com.rtrs.events.aml.AmlClearedEvent.Builder setMetadata(com.rtrs.events.common.EventMetadata value) {
      validate(fields()[0], value);
      this.metadataBuilder = null;
      this.metadata = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'metadata' field has been set.
      * @return True if the 'metadata' field has been set, false otherwise.
      */
    public boolean hasMetadata() {
      return fieldSetFlags()[0];
    }

    /**
     * Gets the Builder instance for the 'metadata' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.rtrs.events.common.EventMetadata.Builder getMetadataBuilder() {
      if (metadataBuilder == null) {
        if (hasMetadata()) {
          setMetadataBuilder(com.rtrs.events.common.EventMetadata.newBuilder(metadata));
        } else {
          setMetadataBuilder(com.rtrs.events.common.EventMetadata.newBuilder());
        }
      }
      return metadataBuilder;
    }

    /**
     * Sets the Builder instance for the 'metadata' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.rtrs.events.aml.AmlClearedEvent.Builder setMetadataBuilder(com.rtrs.events.common.EventMetadata.Builder value) {
      clearMetadata();
      metadataBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'metadata' field has an active Builder instance
     * @return True if the 'metadata' field has an active Builder instance
     */
    public boolean hasMetadataBuilder() {
      return metadataBuilder != null;
    }

    /**
      * Clears the value of the 'metadata' field.
      * @return This builder.
      */
    public com.rtrs.events.aml.AmlClearedEvent.Builder clearMetadata() {
      metadata = null;
      metadataBuilder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'tradeId' field.
      * @return The value.
      */
    public java.lang.String getTradeId() {
      return tradeId;
    }


    /**
      * Sets the value of the 'tradeId' field.
      * @param value The value of 'tradeId'.
      * @return This builder.
      */
    public com.rtrs.events.aml.AmlClearedEvent.Builder setTradeId(java.lang.String value) {
      validate(fields()[1], value);
      this.tradeId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'tradeId' field has been set.
      * @return True if the 'tradeId' field has been set, false otherwise.
      */
    public boolean hasTradeId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'tradeId' field.
      * @return This builder.
      */
    public com.rtrs.events.aml.AmlClearedEvent.Builder clearTradeId() {
      tradeId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'accountId' field.
      * @return The value.
      */
    public java.lang.String getAccountId() {
      return accountId;
    }


    /**
      * Sets the value of the 'accountId' field.
      * @param value The value of 'accountId'.
      * @return This builder.
      */
    public com.rtrs.events.aml.AmlClearedEvent.Builder setAccountId(java.lang.String value) {
      validate(fields()[2], value);
      this.accountId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'accountId' field has been set.
      * @return True if the 'accountId' field has been set, false otherwise.
      */
    public boolean hasAccountId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'accountId' field.
      * @return This builder.
      */
    public com.rtrs.events.aml.AmlClearedEvent.Builder clearAccountId() {
      accountId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'riskScore' field.
      * AML risk score 0-100, threshold is 70
      * @return The value.
      */
    public int getRiskScore() {
      return riskScore;
    }


    /**
      * Sets the value of the 'riskScore' field.
      * AML risk score 0-100, threshold is 70
      * @param value The value of 'riskScore'.
      * @return This builder.
      */
    public com.rtrs.events.aml.AmlClearedEvent.Builder setRiskScore(int value) {
      validate(fields()[3], value);
      this.riskScore = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'riskScore' field has been set.
      * AML risk score 0-100, threshold is 70
      * @return True if the 'riskScore' field has been set, false otherwise.
      */
    public boolean hasRiskScore() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'riskScore' field.
      * AML risk score 0-100, threshold is 70
      * @return This builder.
      */
    public com.rtrs.events.aml.AmlClearedEvent.Builder clearRiskScore() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'clearedAt' field.
      * @return The value.
      */
    public java.time.Instant getClearedAt() {
      return clearedAt;
    }


    /**
      * Sets the value of the 'clearedAt' field.
      * @param value The value of 'clearedAt'.
      * @return This builder.
      */
    public com.rtrs.events.aml.AmlClearedEvent.Builder setClearedAt(java.time.Instant value) {
      validate(fields()[4], value);
      this.clearedAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'clearedAt' field has been set.
      * @return True if the 'clearedAt' field has been set, false otherwise.
      */
    public boolean hasClearedAt() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'clearedAt' field.
      * @return This builder.
      */
    public com.rtrs.events.aml.AmlClearedEvent.Builder clearClearedAt() {
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AmlClearedEvent build() {
      try {
        AmlClearedEvent record = new AmlClearedEvent();
        if (metadataBuilder != null) {
          try {
            record.metadata = this.metadataBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("metadata"));
            throw e;
          }
        } else {
          record.metadata = fieldSetFlags()[0] ? this.metadata : (com.rtrs.events.common.EventMetadata) defaultValue(fields()[0]);
        }
        record.tradeId = fieldSetFlags()[1] ? this.tradeId : (java.lang.String) defaultValue(fields()[1]);
        record.accountId = fieldSetFlags()[2] ? this.accountId : (java.lang.String) defaultValue(fields()[2]);
        record.riskScore = fieldSetFlags()[3] ? this.riskScore : (java.lang.Integer) defaultValue(fields()[3]);
        record.clearedAt = fieldSetFlags()[4] ? this.clearedAt : (java.time.Instant) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AmlClearedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<AmlClearedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AmlClearedEvent>
    READER$ = (org.apache.avro.io.DatumReader<AmlClearedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










